### PR TITLE
Storybook@7.0.0-rc.4 update and package upgrades

### PR DESCRIPTION
**Pull request by NickMcBurney**
- Upgrading from `storybook@7.0.0-rc.3` to `storybook@7.0.0-rc.4`
- Upgrading dependencies
- Cleaning `playwright` config
- Fixing some old `storybook@6.x` imports

### CODE REVIEW

**Comment by louia** [comment]
When I try to install this version with :
```bash
npm i storybook-vue3-router@3.0.0-next.1 -D
```

I got this message :
image

**Comment by NickMcBurney** [comment]
@louia, Its best to raise issues in the Issues section rather than on a closed PR. Looking at versions the x-range constraint used in this package `7.x` should work with `7.0.0-rc.8` , this can be confirmed here: https://jubianchi.github.io/semver-check/#/7.x/7.0.0-rc.8

There is a few options which may help:
1. Delete `node_modules` + `package-lock.json`, then run `npm i`
2. If above does not work, then try running `npm install --save --legacy-peer-deps`

Would also be helpful to know what version of node/npm you're running.

Hoping first suggestion fixes for you.

**Comment by NickMcBurney** [comment]
@louia I think I may have resolved the issue - I've just published a new version `3.0.0-next.3`

PR is here: https://github.com/NickMcBurney/storybook-vue3-router/pull/43

I've updated to `@storybook@7.0.0-rc.10` and also amended how `peerDependencies` are specified which I expect should now work for you.

**Comment by louia** [comment]
It fix my problem, thanks !

**Pull request merged**
